export type { WearableRepresentation } from './representation.js'
export { wearableRepresentationSchema } from './representation.js'
export type { Wearable } from './wearable.js'
export { wearableSchema, wearableKeywordDefinitions } from './wearable.js'
export { WearableCategory, wearableCategorySchema } from './wearable-category.js'
export { BodyPartCategory, bodyPartCategorySchema } from './body-part-category.js'
export type { HideableWearableCategory } from './hideable-category.js'
export { hideableWearableCategorySchema } from './hideable-category.js'
